"""Initial

Revision ID: 719b7bfd65c0
Revises: 
Create Date: 2023-06-26 23:24:10.187919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719b7bfd65c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(), nullable=False),
    sa.Column('auditory_number', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classroom_pool',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education_program',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profile_code', sa.String(), nullable=False),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('education_level', sa.Enum('BACHELOR', 'MASTER', 'SPECIALIST', 'POSTGRADUATE', name='educationlevel'), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institution',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chain',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('project', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classroom_equipment',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('classroom', sa.Integer(), nullable=False),
    sa.Column('item', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom'], ['classroom.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classroom_pool_classroom',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('classroom_pool', sa.Integer(), nullable=False),
    sa.Column('classroom', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom'], ['classroom.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['classroom_pool'], ['classroom_pool.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combination',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('project', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('institution', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['institution'], ['institution.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education_block',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('education_program', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['education_program'], ['education_program.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_slot',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('project', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('time_slot_type', sa.Enum('DEFAULT', 'WEEKLY', name='timeslottype'), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('class_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education_module',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('is_base_module', sa.Boolean(), nullable=False),
    sa.Column('education_block', sa.Integer(), nullable=False),
    sa.Column('parent_module', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['education_block'], ['education_block.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_module'], ['education_module.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('department', sa.Integer(), nullable=False),
    sa.Column('education_program', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('part_of', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department'], ['department.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['education_program'], ['education_program.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_of'], ['group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lecturer',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('department', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department'], ['department.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discipline',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('education_module', sa.Integer(), nullable=False),
    sa.Column('assessment', sa.Enum('EXAM', 'ASSESSMENT', 'ASSESSMENT_WITH_GRADE', 'COURSE_PROJECT', 'COURSE_WORK', 'VERIFICATION_WORK', 'GRADE', 'GRAPHIC_WORK', name='assessment'), nullable=False),
    sa.ForeignKeyConstraint(['education_module'], ['education_module.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preference',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('project', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('lecturer', sa.Integer(), nullable=False),
    sa.Column('time_slot', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lecturer'], ['lecturer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_slot'], ['time_slot.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('project', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('discipline', sa.Integer(), nullable=False),
    sa.Column('lecturer', sa.Integer(), nullable=False),
    sa.Column('group', sa.Integer(), nullable=False),
    sa.Column('course_type', sa.Enum('LECTURE', 'PRACTICE', 'LABORATORY', name='coursetype'), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('week_intensity', sa.Integer(), nullable=False),
    sa.Column('block_length', sa.Integer(), nullable=False),
    sa.Column('time_slot_from', sa.Integer(), nullable=True),
    sa.Column('time_slot_to', sa.Integer(), nullable=True),
    sa.Column('classroom_pool', sa.Integer(), nullable=True),
    sa.Column('combination', sa.Integer(), nullable=True),
    sa.Column('chain', sa.Integer(), nullable=True),
    sa.Column('chain_priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chain'], ['chain.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['classroom_pool'], ['classroom_pool.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['combination'], ['combination.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['discipline'], ['discipline.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group'], ['group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lecturer'], ['lecturer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_slot_from'], ['time_slot.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['time_slot_to'], ['time_slot.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('required_equipment',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('discipline', sa.Integer(), nullable=False),
    sa.Column('item', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discipline'], ['discipline.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('required_equipment')
    op.drop_table('course')
    op.drop_table('preference')
    op.drop_table('discipline')
    op.drop_table('lecturer')
    op.drop_table('group')
    op.drop_table('education_module')
    op.drop_table('time_slot')
    op.drop_table('education_block')
    op.drop_table('department')
    op.drop_table('combination')
    op.drop_table('classroom_pool_classroom')
    op.drop_table('classroom_equipment')
    op.drop_table('chain')
    op.drop_table('project')
    op.drop_table('item')
    op.drop_table('institution')
    op.drop_table('education_program')
    op.drop_table('classroom_pool')
    op.drop_table('classroom')
    # ### end Alembic commands ###
