"""Added ClassroomTimeSlot

Revision ID: 95332849c9c2
Revises: 719b7bfd65c0
Create Date: 2023-06-27 00:40:50.641544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95332849c9c2'
down_revision = '719b7bfd65c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom_time_slot',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('classroom', sa.Integer(), nullable=False),
    sa.Column('time_slot', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom'], ['classroom.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_slot'], ['time_slot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classroom_time_slot')
    # ### end Alembic commands ###
